In [11]:
from random import random
from math import ceil
from functools import reduce
from collections import namedtuple, deque
from queue import PriorityQueue

import numpy as np
from tqdm.auto import tqdm

In [12]:
State = namedtuple('State', ['taken', 'not_taken'])

def goal_check(state):
    return np.all(covered(state))

def covered(state):
    return reduce(np.logical_or, [SETS[i] for i in state.taken], np.array([False for _ in range(PROBLEM_SIZE)]))

In [27]:
PROBLEM_SIZE = 10
NUM_SETS = 100
SETS = tuple(np.array([random()<.05 for _ in range(PROBLEM_SIZE)])for _ in range(NUM_SETS))
assert goal_check(State(set(range(NUM_SETS)), set())), "Probelm not solvable"

In [34]:
def f(state):
    return g(state) + h(state)

def g(state):
    return PROBLEM_SIZE - sum(covered(state))

def h(state):
    punti_presi = covered(state)
    free_tessere = min(PROBLEM_SIZE - sum(np.logical_or(punti_presi, SETS[s])) for s in state.not_taken)
    return free_tessere

def h2(state):
    punti_presi = covered(state)
    taken = 0
    while PROBLEM_SIZE - sum(punti_presi) > 0:
        index, _ = min((index, (PROBLEM_SIZE - sum(np.logical_or(punti_presi, SETS[index])))) for index, _ in enumerate(state.not_taken))
        punti_presi = np.logical_or(punti_presi, SETS[index])
        taken+=1
    
    return taken 

def compute_special_set():
    occurrencies = sum(SETS)
    special_set = State(set(), set(range(NUM_SETS)))
    for i in occurrencies:
        if i==1:
            for s in range(len(SETS)):
                if SETS[s][i]:
                    special_set = State(special_set.taken ^ {SETS[s]}, special_set.not_taken ^ {SETS[s]})     # "^" == XOR
    return special_set

In [35]:
frontier = PriorityQueue()

special_set = compute_special_set()

state = special_set      # ({taken}, {not_taken})
frontier.put((f(state), state))       # [ ( {f=g+h}, { {taken}, {not_taken} } ), ]

counter = 0
_ , current_state = frontier.get()
with tqdm(total=None) as pbar:
    while not goal_check(current_state):
        counter += 1
        for tiles in current_state[1]:
            new_state = State(current_state.taken ^ {tiles}, current_state.not_taken ^ {tiles})     # "^" == XOR
            frontier.put((f(new_state), new_state))
        _ ,current_state = frontier.get()
        pbar.update(1)

print(f"Solved in {counter:,} steps ({len(current_state.taken)} tiles)")

TypeError: unhashable type: 'numpy.ndarray'

In [36]:
current_state

State(taken={37, 17, 84, 23, 26, 27}, not_taken={0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 24, 25, 28, 29, 30, 31, 32, 33, 34, 35, 36, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99})

In [37]:
sum(SETS)

array([7, 7, 5, 1, 6, 7, 5, 3, 3, 4])

In [33]:
SETS

(array([False,  True, False, False, False, False, False, False, False,
        False]),
 array([False, False, False, False, False,  True, False, False, False,
        False]),
 array([False, False, False, False, False, False, False, False, False,
        False]),
 array([False, False, False, False, False, False, False, False, False,
        False]),
 array([False, False, False, False, False, False, False, False, False,
        False]),
 array([False, False, False, False, False, False, False, False, False,
        False]),
 array([False, False, False, False, False, False, False, False, False,
        False]),
 array([False, False, False, False, False, False, False, False, False,
        False]),
 array([False, False, False, False, False, False, False, False, False,
        False]),
 array([False, False, False, False, False,  True, False, False, False,
        False]),
 array([False, False, False, False, False, False, False, False, False,
        False]),
 array([False, False, False, Fal