In [17]:
from random import random
from math import ceil
from functools import reduce
from collections import namedtuple, deque
from queue import PriorityQueue

import numpy as np
from tqdm.auto import tqdm

In [40]:
State = namedtuple('State', ['taken', 'not_taken'])

def goal_check(state):
    return np.all(covered(state))

def covered(state):
    return reduce(np.logical_or, [SETS[i] for i in state.taken], np.array([False for _ in range(PROBLEM_SIZE)]))

In [158]:
PROBLEM_SIZE = 20
NUM_SETS = 40
SETS = tuple(np.array([random()<.3 for _ in range(PROBLEM_SIZE)])for _ in range(NUM_SETS))
assert goal_check(State(set(range(NUM_SETS)), set())), "Probelm not solvable"

In [159]:
print(sum(SETS))
SETS

[ 9 11 14 16  9 14 12 14 11 15 11 17 12 10 13 11 13  9 14 13]


(array([False, False, False,  True, False, False, False, False, False,
         True, False,  True, False,  True, False, False,  True, False,
         True,  True]),
 array([False,  True,  True,  True, False,  True,  True, False, False,
        False, False, False,  True, False, False, False,  True, False,
        False, False]),
 array([False, False, False, False, False, False,  True,  True, False,
        False, False, False, False, False, False, False, False, False,
         True, False]),
 array([ True, False,  True, False, False, False,  True, False,  True,
         True, False, False, False, False, False,  True, False, False,
        False, False]),
 array([False, False, False, False, False, False, False, False, False,
         True, False,  True, False,  True,  True,  True,  True, False,
        False, False]),
 array([False,  True, False,  True, False, False, False,  True,  True,
        False, False, False,  True,  True,  True, False, False, False,
        False, False]),
 arr

In [161]:
def f(state):
    return g(state) + h(state)

def g(state):
    return PROBLEM_SIZE - sum(covered(state))

def h(state):
    punti_presi = covered(state)
    free_tessere = min(PROBLEM_SIZE - sum(np.logical_or(punti_presi, SETS[s])) for s in state.not_taken)
    return free_tessere

In [162]:
frontier = PriorityQueue()
state = State(set(), set(range(NUM_SETS)))      # ({taken}, {not_taken})
frontier.put((f(state), state))       # [ ( {f=g+h}, { {taken}, {not_taken} } ), ]

counter = 0
_ , current_state = frontier.get()
while not goal_check(current_state):
    counter += 1
    for tiles in current_state[1]:
        new_state = State(current_state.taken ^ {tiles}, current_state.not_taken ^ {tiles})     # "^" == XOR
        frontier.put((f(new_state), new_state))
    _ ,current_state = frontier.get()

print(f"Solved in {counter:,} steps ({len(current_state.taken)} tiles)")

Solved in 3 steps (3 tiles)


In [163]:
current_state

State(taken={16, 17, 10}, not_taken={0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39})

In [164]:
SETS[10]

array([False,  True,  True,  True, False,  True,  True, False,  True,
        True, False,  True, False, False, False, False, False,  True,
       False,  True])

In [165]:
SETS[16]

array([ True, False, False, False, False, False, False,  True, False,
       False,  True, False, False,  True, False,  True,  True, False,
        True, False])

In [166]:
SETS[17]

array([False, False,  True,  True,  True, False, False, False, False,
       False, False,  True,  True, False,  True, False, False, False,
       False,  True])